name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  audit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.3.0]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run security-audit

  build:
    runs-on: ubuntu-latest
    needs: audit

    strategy:
      matrix:
        node-version: [16.3.0]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run:
          npm cache clean
          npm ci

  test:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        node-version: [16.3.0]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - 
        env:
          HTTP_PORT: ${{ secrets.HTTP_PORT }}
          HTTPS_PORT: ${{ secrets.HTTPS_PORT }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          MAILGUN_SMTP_LOGIN: ${{ secrets.MAILGUN_SMTP_LOGIN }}
          MAILGUN_SMTP_PASSWORD: ${{ secrets.MAILGUN_SMTP_PASSWORD }}
        run: npm test
